# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param X numeric matrix
#' @param Y numeric vector
#' @return the inverse of \code{t(X)%*%Y}
lrm_coef <- function(X, Y) {
    .Call('_LRM_lrm_coef', PACKAGE = 'LRM', X, Y)
}

